// ─────────────────────────────────────────────────────────────────────────────
// src/firebase/qcTemplateSeed.ts
//
// Default Rite Solar Post-Installation QC checklist.
// Generated from RiteSolar_PostInstall_QA_Checklist_2.1.xlsx.
//
//   54 check points across 7 sections
//   21 Critical · 23 Major · 10 Minor
//   24 points require a photo even to PASS
//   5 points are typed 'measurement' so the app can range-check the value
//     (3.3 earth resistance, 4.3 production check, 5.1 Voc, 5.2 Isc, 5.3 IR)
//
// Seeded into appConfig/global.qcTemplate by initQcConfig() — which must check
// for the key individually, because initAppConfig early-returns on an existing
// config doc (initAppConfig.ts:160-162) and would never reach a live install.
//
// Admins edit this afterwards in Template → QC Checklist. A job version-locks
// its own copy at creation, so template edits apply to NEW jobs only.
//
// TODO before rollout — see §9 of the change plan:
//   • 5.1 / 5.2 expectedMin/Max must be derived from the module datasheet and
//     string length; they are intentionally left undefined here.
//   • 5.3 expectedMin is a placeholder — set it to your IR standard.
//   • §5 is "when fault occurs" and §6 is "at handover": add showIf rules or
//     accept N/A on a commissioning-day inspection.
// ─────────────────────────────────────────────────────────────────────────────
import type { QcFieldDefinition } from '@/types/qc';

export const QC_TEMPLATE_VERSION = 1;

export const DEFAULT_QC_TEMPLATE: QcFieldDefinition[] = [
  // ── 1. Structural & Mounting Integrity ──────────────────────────────────
  {
    fieldId: 'qc_sec_1', type: 'section_header', sortOrder: 0,
    label: '1. Structural & Mounting Integrity',
    isRequired: false, options: [],
  },
  {
    fieldId: 'qc_1_1', code: '1.1', type: 'passfail', sortOrder: 1,
    label: 'Structural material',
    verifyText: 'Mounting structure is Hot-Dip Galvanized Iron (HDGI) or aluminium — not painted mild steel',
    target: 'HDGI / Aluminium', method: 'Visual + material cert',
    severity: 'critical', photoRequired: true,
    minPhotos: 1, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_1_2', code: '1.2', type: 'passfail', sortOrder: 2,
    label: 'Tilt & orientation',
    verifyText: 'Panels face true south (N. Hemisphere) at design tilt for max annual generation',
    target: 'True south; design tilt ±5°', method: 'Compass / app',
    severity: 'major', photoRequired: true,
    minPhotos: 1, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_1_3', code: '1.3', type: 'passfail', sortOrder: 3,
    label: 'Roof penetrations sealed',
    verifyText: 'All anchor points sealed with polyurethane (or equivalent) waterproof sealant',
    target: 'No unsealed penetrations', method: 'Visual',
    severity: 'critical', photoRequired: true,
    minPhotos: 1, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_1_4', code: '1.4', type: 'passfail', sortOrder: 4,
    label: 'Panel spacing / self-shading',
    verifyText: 'Sufficient inter-row spacing; no self-shading during low-sun hours',
    target: 'Per shadow analysis', method: 'Visual / measure',
    severity: 'major', photoRequired: false,
    minPhotos: 0, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_1_5', code: '1.5', type: 'passfail', sortOrder: 5,
    label: 'No walking / micro-crack damage',
    verifyText: 'Panel glass free of scratches, cracks, snail trails; crews never stepped on modules',
    target: 'No visible damage', method: 'Visual under reflection',
    severity: 'critical', photoRequired: true,
    minPhotos: 1, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_1_6', code: '1.6', type: 'passfail', sortOrder: 6,
    label: 'Structure fastened',
    verifyText: 'Mounting structure securely fastened to roof/base',
    target: 'Firm, no movement', method: 'Manual push test',
    severity: 'critical', photoRequired: false,
    minPhotos: 0, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_1_7', code: '1.7', type: 'passfail', sortOrder: 7,
    label: 'Torque',
    verifyText: 'All nuts and bolts tightened to specified torque',
    target: 'Per torque spec', method: 'Torque wrench',
    severity: 'major', photoRequired: false,
    minPhotos: 0, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_1_8', code: '1.8', type: 'passfail', sortOrder: 8,
    label: 'Corrosion protection',
    verifyText: 'Corrosion protection / anti-rust applied at cut edges & welds',
    target: 'Applied everywhere', method: 'Visual',
    severity: 'major', photoRequired: false,
    minPhotos: 0, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_1_9', code: '1.9', type: 'passfail', sortOrder: 9,
    label: 'Module clamps',
    verifyText: 'Correct mid/end clamps used; clamped within manufacturer\'s clamping zone',
    target: 'Within clamp zone', method: 'Visual / measure',
    severity: 'major', photoRequired: false,
    minPhotos: 0, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_1_10', code: '1.10', type: 'passfail', sortOrder: 10,
    label: 'Wind/ballast design',
    verifyText: 'Structure design (wind speed, ballast/anchoring) matches local wind zone',
    target: 'Per site wind zone', method: 'Design doc check',
    severity: 'major', photoRequired: false,
    minPhotos: 0, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_1_11', code: '1.11', type: 'passfail', sortOrder: 11,
    label: 'Foundation concreting',
    verifyText: 'Concrete (PCC) cast for all foundation legs / base plates; fully set and level',
    target: 'All legs concreted', method: 'Visual',
    severity: 'critical', photoRequired: true,
    minPhotos: 1, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  // ── 2. Electrical & Cable Management ────────────────────────────────────
  {
    fieldId: 'qc_sec_2', type: 'section_header', sortOrder: 12,
    label: '2. Electrical & Cable Management',
    isRequired: false, options: [],
  },
  {
    fieldId: 'qc_2_1', code: '2.1', type: 'passfail', sortOrder: 13,
    label: 'Conduit protection',
    verifyText: 'All DC & AC cables run through rigid UV-resistant PVC (RPVC) or metal conduit',
    target: 'No loose/exposed wiring', method: 'Visual',
    severity: 'critical', photoRequired: true,
    minPhotos: 1, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_2_2', code: '2.2', type: 'passfail', sortOrder: 14,
    label: 'MC4 connectors',
    verifyText: 'Panel-to-panel joins use proper crimped & locked MC4 connectors — no taped joints',
    target: 'Genuine MC4, locked', method: 'Visual / pull test',
    severity: 'critical', photoRequired: true,
    minPhotos: 1, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_2_3', code: '2.3', type: 'passfail', sortOrder: 15,
    label: 'Cable sag / dressing',
    verifyText: 'Wiring neatly tied to racking rails with UV-resistant cable ties; no roof contact',
    target: 'No sag / roof contact', method: 'Visual',
    severity: 'minor', photoRequired: false,
    minPhotos: 0, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_2_4', code: '2.4', type: 'passfail', sortOrder: 16,
    label: 'Cable size',
    verifyText: 'DC & AC cable sizing correct for current & voltage-drop limits',
    target: 'Voltage drop < 3%', method: 'Design doc / measure',
    severity: 'major', photoRequired: false,
    minPhotos: 0, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_2_5', code: '2.5', type: 'passfail', sortOrder: 17,
    label: 'DC string polarity',
    verifyText: 'String polarity verified correct (no reverse connections)',
    target: 'Correct polarity', method: 'Multimeter',
    severity: 'critical', photoRequired: false,
    minPhotos: 0, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_2_6', code: '2.6', type: 'passfail', sortOrder: 18,
    label: 'Cable labelling',
    verifyText: 'Strings, DC+/-, AC phases and earth conductors clearly labelled',
    target: 'All labelled', method: 'Visual',
    severity: 'minor', photoRequired: false,
    minPhotos: 0, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_2_7', code: '2.7', type: 'passfail', sortOrder: 19,
    label: 'Colour coding',
    verifyText: 'Conductor colour coding follows standard (earth green/green-yellow, etc.)',
    target: 'Per code', method: 'Visual',
    severity: 'minor', photoRequired: false,
    minPhotos: 0, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  // ── 3. Earthing (Grounding) & Safety Devices ────────────────────────────
  {
    fieldId: 'qc_sec_3', type: 'section_header', sortOrder: 20,
    label: '3. Earthing (Grounding) & Safety Devices',
    isRequired: false, options: [],
  },
  {
    fieldId: 'qc_3_1', code: '3.1', type: 'passfail', sortOrder: 21,
    label: 'DC-side earthing',
    verifyText: 'Panel frames & mounting structure earthed (separate earth line)',
    target: 'Continuous bond', method: 'Visual + continuity',
    severity: 'critical', photoRequired: true,
    minPhotos: 1, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_3_2', code: '3.2', type: 'passfail', sortOrder: 22,
    label: 'AC-side earthing',
    verifyText: 'Inverter casing & distribution boxes earthed (separate earth line)',
    target: 'Continuous bond', method: 'Visual + continuity',
    severity: 'critical', photoRequired: false,
    minPhotos: 0, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_3_3', code: '3.3', type: 'measurement', sortOrder: 23,
    label: 'Earth resistance',
    verifyText: 'Earth resistivity measured with tester',
    target: '≤ 5 Ω (ideally)', method: 'Earth tester',
    severity: 'critical', photoRequired: true,
    minPhotos: 1, maxPhotos: 5,
    unit: '\u03a9', expectedMax: 5,   // Earth resistance must be at or below 5 ohm
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_3_4', code: '3.4', type: 'passfail', sortOrder: 24,
    label: 'SPDs fitted',
    verifyText: 'Surge Protection Devices present in DCDB & ACDB to protect inverter',
    target: 'DC + AC SPD present', method: 'Visual',
    severity: 'critical', photoRequired: true,
    minPhotos: 1, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_3_5', code: '3.5', type: 'passfail', sortOrder: 25,
    label: 'MCBs / MCCBs',
    verifyText: 'Correctly rated breakers to isolate power under fault',
    target: 'Correctly rated', method: 'Visual / rating check',
    severity: 'critical', photoRequired: false,
    minPhotos: 0, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_3_6', code: '3.6', type: 'passfail', sortOrder: 26,
    label: 'DCDB present',
    verifyText: 'Dedicated DC Distribution Box installed, IP-rated, UV-protected',
    target: 'Installed & rated', method: 'Visual',
    severity: 'major', photoRequired: true,
    minPhotos: 1, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_3_7', code: '3.7', type: 'passfail', sortOrder: 27,
    label: 'ACDB present',
    verifyText: 'Dedicated AC Distribution Box installed, IP-rated',
    target: 'Installed & rated', method: 'Visual',
    severity: 'major', photoRequired: true,
    minPhotos: 1, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_3_8', code: '3.8', type: 'passfail', sortOrder: 28,
    label: 'Lightning arrestor',
    verifyText: 'Lightning arrestor installed & earthed (if in design scope)',
    target: 'Installed if in scope', method: 'Visual',
    severity: 'major', photoRequired: false,
    minPhotos: 0, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_3_9', code: '3.9', type: 'passfail', sortOrder: 29,
    label: 'MC4 crimping',
    verifyText: 'MC4 connectors properly crimped, locked and UV-protected',
    target: 'Crimped & locked', method: 'Visual / pull',
    severity: 'major', photoRequired: false,
    minPhotos: 0, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_3_10', code: '3.10', type: 'passfail', sortOrder: 30,
    label: 'DC isolator',
    verifyText: 'DC isolator installed and functional (isolates array on demand)',
    target: 'Functional', method: 'Switch test',
    severity: 'critical', photoRequired: false,
    minPhotos: 0, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_3_11', code: '3.11', type: 'passfail', sortOrder: 31,
    label: 'AC isolator',
    verifyText: 'Proper AC isolator installed between inverter and grid/load',
    target: 'Installed & rated', method: 'Visual / test',
    severity: 'critical', photoRequired: false,
    minPhotos: 0, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  // ── 4. Inverter & Commissioning Checks ──────────────────────────────────
  {
    fieldId: 'qc_sec_4', type: 'section_header', sortOrder: 32,
    label: '4. Inverter & Commissioning Checks',
    isRequired: false, options: [],
  },
  {
    fieldId: 'qc_4_1', code: '4.1', type: 'passfail', sortOrder: 33,
    label: 'Location & ventilation',
    verifyText: 'Inverter in shaded, well-ventilated area; not in direct sun / enclosed heat',
    target: 'Shaded, ventilated', method: 'Visual',
    severity: 'major', photoRequired: true,
    minPhotos: 1, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_4_2', code: '4.2', type: 'passfail', sortOrder: 34,
    label: 'Mounting',
    verifyText: 'Inverter firmly wall-mounted at correct height with clearance around it',
    target: 'Firm; clearance OK', method: 'Visual',
    severity: 'minor', photoRequired: false,
    minPhotos: 0, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_4_3', code: '4.3', type: 'measurement', sortOrder: 35,
    label: 'Production check',
    verifyText: 'At clear-sky noon, output is 70–80% of rated capacity (after losses)',
    target: '70–80% of rated kW', method: 'Inverter display / app',
    severity: 'critical', photoRequired: true,
    minPhotos: 1, maxPhotos: 5,
    unit: '%', expectedMin: 70, expectedMax: 80,   // Noon output as % of rated capacity
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_4_4', code: '4.4', type: 'passfail', sortOrder: 36,
    label: 'Anti-islanding test',
    verifyText: 'Switch off grid breaker — inverter shuts down within seconds',
    target: 'Trips within seconds', method: 'Live test',
    severity: 'critical', photoRequired: false,
    minPhotos: 0, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_4_5', code: '4.5', type: 'passfail', sortOrder: 37,
    label: 'Utility settings configured',
    verifyText: 'Inverter grid/protection settings configured as per utility (DISCOM) requirements',
    target: 'Per utility spec', method: 'Inverter menu',
    severity: 'major', photoRequired: false,
    minPhotos: 0, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_4_6', code: '4.6', type: 'passfail', sortOrder: 38,
    label: 'Starts without alarms',
    verifyText: 'Inverter powers up and starts without alarms; generation verified',
    target: 'No alarms; generating', method: 'Inverter display / app',
    severity: 'critical', photoRequired: true,
    minPhotos: 1, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_4_7', code: '4.7', type: 'passfail', sortOrder: 39,
    label: 'No fault / error codes',
    verifyText: 'Inverter display shows no active fault, fault or warning codes',
    target: 'No active faults', method: 'Inverter display',
    severity: 'critical', photoRequired: false,
    minPhotos: 0, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_4_8', code: '4.8', type: 'passfail', sortOrder: 40,
    label: 'Grid parameters',
    verifyText: 'Grid voltage & frequency within window; inverter syncing normally',
    target: 'Within limits', method: 'Inverter display',
    severity: 'major', photoRequired: false,
    minPhotos: 0, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_4_9', code: '4.9', type: 'passfail', sortOrder: 41,
    label: 'Monitoring / RMS live',
    verifyText: 'Remote monitoring (RMS/app/Wi-Fi/GSM) commissioned and reporting data',
    target: 'Live on portal/app', method: 'App / portal',
    severity: 'major', photoRequired: true,
    minPhotos: 1, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_4_10', code: '4.10', type: 'passfail', sortOrder: 42,
    label: 'Net-meter / bidirectional',
    verifyText: 'Net / bidirectional meter installed and recording import & export',
    target: 'Import & export logged', method: 'Meter reading',
    severity: 'major', photoRequired: true,
    minPhotos: 1, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  // ── 5. Testing & Measurements- (when Fault Occure) ──────────────────────
  {
    fieldId: 'qc_sec_5', type: 'section_header', sortOrder: 43,
    label: '5. Testing & Measurements- (when Fault Occure)',
    isRequired: false, options: [],
  },
  {
    fieldId: 'qc_5_1', code: '5.1', type: 'measurement', sortOrder: 44,
    label: 'Open Circuit Voltage (Voc)',
    verifyText: 'String Voc measured and recorded; matches expected design value',
    target: 'Within expected range', method: 'Multimeter',
    severity: 'major', photoRequired: true,
    minPhotos: 1, maxPhotos: 5,
    unit: 'V',   // String Voc — set bounds from the module datasheet x string length
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_5_2', code: '5.2', type: 'measurement', sortOrder: 45,
    label: 'Short Circuit Current (Isc)',
    verifyText: 'String Isc measured and recorded; matches expected design value',
    target: 'Within expected range', method: 'Clamp meter',
    severity: 'major', photoRequired: true,
    minPhotos: 1, maxPhotos: 5,
    unit: 'A',   // String Isc — set bounds from the module datasheet
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_5_3', code: '5.3', type: 'measurement', sortOrder: 46,
    label: 'Insulation Resistance (IR)',
    verifyText: 'IR (megger) test on DC & AC circuits passed',
    target: 'Passes IR test', method: 'Megger',
    severity: 'critical', photoRequired: true,
    minPhotos: 1, maxPhotos: 5,
    unit: 'M\u03a9', expectedMin: 1,   // Insulation resistance — set expectedMin per your standard
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_5_4', code: '5.4', type: 'passfail', sortOrder: 47,
    label: 'Earth continuity',
    verifyText: 'Earth continuity test passed across all bonded parts',
    target: 'Continuous / passes', method: 'Continuity tester',
    severity: 'critical', photoRequired: false,
    minPhotos: 0, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  // ── 6. Documentation & Handover (at the time of handover) ───────────────
  {
    fieldId: 'qc_sec_6', type: 'section_header', sortOrder: 48,
    label: '6. Documentation & Handover (at the time of handover)',
    isRequired: false, options: [],
  },
  {
    fieldId: 'qc_6_1', code: '6.1', type: 'passfail', sortOrder: 49,
    label: 'Single-line diagram',
    verifyText: 'As-built single-line diagram (SLD) available',
    target: 'Provided', method: 'Doc check',
    severity: 'major', photoRequired: false,
    minPhotos: 0, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_6_2', code: '6.2', type: 'passfail', sortOrder: 50,
    label: 'Warranty documents',
    verifyText: 'Panel, inverter & workmanship warranty documents handed over',
    target: 'Handed over', method: 'Doc check',
    severity: 'major', photoRequired: false,
    minPhotos: 0, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_6_3', code: '6.3', type: 'passfail', sortOrder: 51,
    label: 'O&M manual',
    verifyText: 'Operation & maintenance manual provided to customer',
    target: 'Provided', method: 'Doc check',
    severity: 'major', photoRequired: false,
    minPhotos: 0, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_6_4', code: '6.4', type: 'passfail', sortOrder: 52,
    label: 'Datasheets / serials',
    verifyText: 'Module & inverter serial numbers recorded; datasheets included',
    target: 'Recorded', method: 'Doc check',
    severity: 'minor', photoRequired: true,
    minPhotos: 1, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_6_5', code: '6.5', type: 'passfail', sortOrder: 53,
    label: 'Subsidy / DISCOM docs',
    verifyText: 'PM Surya Ghar / DISCOM net-metering & subsidy paperwork status confirmed',
    target: 'Status confirmed', method: 'Doc check',
    severity: 'major', photoRequired: false,
    minPhotos: 0, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_6_6', code: '6.6', type: 'passfail', sortOrder: 54,
    label: 'Customer walkthrough',
    verifyText: 'Customer shown app, shutdown procedure, cleaning & safety do\'s/don\'ts',
    target: 'Walkthrough done', method: 'On-site briefing',
    severity: 'minor', photoRequired: false,
    minPhotos: 0, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_6_7', code: '6.7', type: 'passfail', sortOrder: 55,
    label: 'Site photos',
    verifyText: 'Before/after & component photos captured for records',
    target: 'Photos on file', method: 'Camera',
    severity: 'minor', photoRequired: true,
    minPhotos: 1, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  // ── 7. Site Cleanliness & Final (instructions in scope of installer) ────
  {
    fieldId: 'qc_sec_7', type: 'section_header', sortOrder: 56,
    label: '7. Site Cleanliness & Final (instructions in scope of installer)',
    isRequired: false, options: [],
  },
  {
    fieldId: 'qc_7_1', code: '7.1', type: 'passfail', sortOrder: 57,
    label: 'Site cleared',
    verifyText: 'All installation debris, packaging & offcuts removed from site',
    target: 'Site clean', method: 'Visual',
    severity: 'minor', photoRequired: false,
    minPhotos: 0, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_7_2', code: '7.2', type: 'passfail', sortOrder: 58,
    label: 'Panels clean',
    verifyText: 'Modules wiped clean; no dust, cement, footmarks or adhesive residue',
    target: 'Clean surface', method: 'Visual',
    severity: 'minor', photoRequired: true,
    minPhotos: 1, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_7_3', code: '7.3', type: 'passfail', sortOrder: 59,
    label: 'Safety signage',
    verifyText: 'Warning labels / caution signage on DCDB, ACDB, inverter as required',
    target: 'Signage present', method: 'Visual',
    severity: 'minor', photoRequired: false,
    minPhotos: 0, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
  {
    fieldId: 'qc_7_4', code: '7.4', type: 'passfail', sortOrder: 60,
    label: 'Customer sign-off',
    verifyText: 'Customer inspection sign-off obtained',
    target: 'Signed', method: 'Sign-off form',
    severity: 'major', photoRequired: true,
    minPhotos: 1, maxPhotos: 5,
    isRequired: true, allowNA: true, remarkRequiredOnFail: true,
    photoRequiredOnFail: true, options: [],
  },
];

// ── Declaration texts shown above each signature pad ─────────────────────────
// Stored in appConfig/global.declarationTexts so legal can revise them without
// a deploy. The exact text a signer accepted is copied into SignOff.declaration.
export const DECLARATIONS = {
  inspector:
    'I certify that the above inspection was carried out by me at this site on ' +
    'the date and time shown, and that the recorded observations, measurements ' +
    'and photographs are a true record of the installation as found.',
  customer:
    'I confirm that the installation was shown to me, that the system operation, ' +
    'shutdown procedure and cleaning instructions were explained to me, and that ' +
    'I have received the handover documents listed above.',
  approver:
    'I have reviewed the inspection record and the supporting evidence in full ' +
    'and record the verdict stated above.',
} as const;
